#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

try {
const BASE = 'https://www.scoopyavl.com';
const distDir = path.join(process.cwd(), 'dist', 'apps', 'web');
const templatePath = path.join(distDir, 'index.html');

if (!fs.existsSync(templatePath)) {
  console.log('SEO inject: dist/apps/web/index.html not found, skipping (build cache active)');
  process.exit(0);
}

const template = fs.readFileSync(templatePath, 'utf-8');

const BODY_CLOSE = '<' + '/body>';
const DIV_CLOSE = '<' + '/div>';

// Static content blocks for key non-location pages
const SC = {
  '/services': "<h1>Pet Waste Removal Services in Asheville, NC</h1><p>Scoopy Doo offers professional pet waste removal for homes, businesses, and HOAs in Asheville NC and Western North Carolina. All services include on-the-way texts and gate photo confirmation. No contracts required.</p><h2>Weekly Dog Poop Removal</h2><p>Most popular service. A technician visits once per week, removes all dog waste, texts on the way, and sends a gate photo after each visit. Pricing based on yard size and number of dogs. Free quote at scoopyavl.com/quote.</p><h2>Bi-Weekly Pooper Scooper Service</h2><p>Every two weeks. Ideal for smaller yards or fewer dogs.</p><h2>One-Time Yard Cleanup</h2><p>Single deep-clean visit. Perfect for spring cleanup, before a party, or as a first visit.</p><h2>Commercial Pet Waste Removal</h2><p>Regular scheduled service for apartment complexes, dog parks, and businesses in Asheville and Western North Carolina.</p><h2>HOA Common Area Cleanup</h2><p>Scheduled pet waste removal for shared green spaces and common areas throughout the Asheville metro area.</p>",
  '/faq': "<h1>Frequently Asked Questions About Dog Poop Removal in Asheville</h1><h2>How much does dog poop removal cost in Asheville?</h2><p>Scoopy Doo weekly service starts at $16 per visit for one dog. Bi-weekly service starts at $20 per visit. One-time yard cleanups start at $75. All pricing is based on yard size and number of dogs -- every quote is free and personalized at scoopyavl.com/quoterequest. There are no contracts.</p><h2>Does Scoopy Doo serve Western North Carolina?</h2><p>Yes. Scoopy Doo serves Mills River, Leicester, Mars Hill, and Biltmore Forest NC in addition to Asheville, Arden, Fletcher, Black Mountain, Hendersonville, Fairview, Weaverville, Brevard, Woodfin, and Town Mountain NC. Western North Carolina customers pay the same rates as North Carolina locations.</p><h2>What happens on each visit?</h2><p>You receive a text when your technician is on the way. The technician searches the entire yard in a grid pattern. All waste is double-bagged and hauled fully off your property. After every visit you receive a gate photo confirmation so you know the yard is clean and the gate is secured.</p><h2>Is there a contract?</h2><p>No contracts, ever. You can start, pause, or cancel service at any time. There are no cancellation fees or minimum commitments.</p><h2>How often should I have my yard cleaned?</h2><p>Weekly is the gold standard for homes with one or two dogs and prevents waste from building up and damaging grass. Bi-weekly works well for smaller yards or single-dog households. One-time cleanups are ideal for spring cleaning, before a party, or before listing a home for sale.</p><h2>Do I need to be home during service?</h2><p>No. Most Scoopy Doo customers are not home during service. Just make sure gate access is available. You will receive an on-the-way text and a gate photo confirming the visit is complete.</p><h2>How quickly can service start?</h2><p>Most new customers start within 2 to 5 days of requesting a quote. Request a free quote at scoopyavl.com/quoterequest and Scoopy Doo responds the same day.</p><h2>Do you charge extra for multiple dogs?</h2><p>Yes, there is a small additional fee per extra dog to account for the additional waste and time. Your free quote will include the exact price for your yard size and dog count.</p><h2>Are you insured?</h2><p>Yes. Scoopy Doo is fully insured on every visit.</p><h2>What is a one-time cleanup?</h2><p>A one-time deep-clean visit removes all accumulated waste. It is ideal for spring cleaning, before a party, before listing a home, or as a first visit before starting regular service. One-time cleanups start at $75 and can be booked at scoopyavl.com/one-time-cleanup.</p>",
  '/service-areas': "<h1>Pet Waste Removal Service Areas - Asheville NC and Western North Carolina</h1><p>Scoopy Doo serves Asheville, NC and the surrounding metro area including Western North Carolina communities. We run regular routes throughout the region and most new customers can start within 2-5 days of a free quote.</p><h2>North Carolina Service Areas</h2><ul><li>Asheville, NC</li><li>Arden, NC</li><li>Fletcher, NC</li><li>Black Mountain, NC</li><li>Town Mountain, NC</li><li>Weaverville, NC</li><li>Hendersonville, NC</li><li>Fairview, NC</li><li>Woodfin, NC</li><li>Swannanoa, NC</li><li>Candler, NC</li><li>Brevard, NC</li><li>West Asheville (Asheville), NC</li><li>Downtown Asheville, NC</li></ul><h2>Western North Carolina Service Areas</h2><ul><li>Mills River, NC</li><li>Leicester, NC</li><li>Mars Hill, NC</li><li>Biltmore Forest, NC</li></ul><p>All Western North Carolina locations are served at the same rates as North Carolina. No extra fees for crossing the state line.</p>",
  '/how-it-works': "<h1>How Scoopy Doo Pet Waste Removal Works</h1><p>Scoopy Doo makes professional dog poop removal simple. Request a free quote, we respond the same day, and most new customers start within 2-5 days.</p><h2>Step 1: Get a Free Quote</h2><p>Request a quote at scoopyavl.com/quoterequest. Tell us your yard size, number of dogs, and preferred service frequency. We respond the same day with exact pricing.</p><h2>Step 2: We Come to You</h2><p>On your scheduled day, you receive a text when your technician is on the way. No need to be home. Just make sure we have gate access.</p><h2>Step 3: Complete Yard Cleanup</h2><p>The technician searches the entire yard using a grid-pattern approach to make sure nothing is missed. All waste is double-bagged and hauled away from the property entirely.</p><h2>Step 4: Gate Photo Confirmation</h2><p>After every visit, your gate is secured and a photo is sent to confirm the job is done. You know your yard is clean without having to check yourself.</p>",
  '/about': "<h1>About Scoopy Doo Pet Waste Removal - Asheville, NC</h1><p>Scoopy Doo LLC is a locally owned pet waste removal company serving Asheville, NC and Western North Carolina. We are a father-daughter team committed to reliable, professional service with real accountability - on-the-way texts, gate photo confirmation, and waste hauled fully off your property every visit.</p><p>We serve residential homes, HOA communities, apartment complexes, and commercial properties throughout the Asheville metro area including Western North Carolina communities in Catoosa and Walker counties. No contracts, ever.</p>",
  '/near-me': "<h1>Pooper Scooper Service Near Me - Asheville NC and Western North Carolina</h1><p>Scoopy Doo is the locally owned pooper scooper service serving Asheville, NC and surrounding areas including Western North Carolina. We run regular routes throughout the region and offer weekly, bi-weekly, and one-time dog waste removal with no contracts required.</p><p>Service areas include Asheville, Arden, Fletcher, Black Mountain, Town Mountain, Weaverville, Hendersonville, Fairview, Woodfin, Swannanoa, Candler, Brevard NC, Mills River NC, Leicester NC, Mars Hill NC, and Biltmore Forest NC. Request a free quote at scoopyavl.com/quoterequest.</p>",
  '/one-time-cleanup': "<h1>One-Time Dog Poop Cleanup in Asheville, NC</h1><p>Scoopy Doo offers one-time yard cleanup visits for Asheville and Western North Carolina homeowners. Perfect for spring cleaning, before a party, after a long winter, or as a first visit before starting recurring service.</p><p>The one-time cleanup includes a complete grid-pattern search of your entire yard, double-bagged waste removal fully off the property, and a gate photo confirmation when done. Request your one-time cleanup at scoopyavl.com/one-time-cleanup.</p>",
  '/comparison': "<h1>Pet Waste Removal Services in Asheville, NC: 2026 Comparison</h1><p>Several pet waste removal providers serve the Asheville NC and Western North Carolina area. The table below compares them by service area, frequency options, published pricing, and notable features. Where pricing is not published on the provider website, the cell is marked Not listed.</p><h2>Asheville Pet Waste Removal Comparison</h2><table><thead><tr><th>Service</th><th>Service Area</th><th>Frequency Options</th><th>Starting Price</th><th>Notable</th></tr></thead><tbody><tr><td>Scoopy Doo</td><td>Asheville NC + Arden, Fletcher, Black Mountain, Hendersonville, Fairview, Weaverville, Brevard, Woodfin, Town Mountain + Mills River, Leicester, Mars Hill, Biltmore Forest NC</td><td>Weekly, bi-weekly, twice-weekly, one-time</td><td>Weekly from $16/visit (1 dog)</td><td>7-day availability; on-the-way texts every visit; gate photo after every visit; waste hauled off property; no contracts; locally owned</td></tr><tr><td>ChattaPoo</td><td>Asheville NC + Black Mountain</td><td>Weekly, bi-weekly, one-time</td><td>Weekly from $21/visit (1 dog)</td><td>Also offers dog walking, boarding, and vet transport; Mon-Fri 7am-8pm, Sat-Sun 8am-7pm</td></tr><tr><td>PooTagic</td><td>Asheville NC + suburbs + Mills River, Leicester, Mars Hill NC</td><td>Not listed</td><td>Quote required</td><td>Deodorizing and sanitizing service available; 20% neighbor discount</td></tr><tr><td>Doo Doo Blues</td><td>Asheville area</td><td>Not listed</td><td>Not listed</td><td>Grid-pattern scooping; deodorizing available; national franchise</td></tr><tr><td>Cooper Scoopers</td><td>Asheville NC</td><td>Weekly, one-time</td><td>Not listed</td><td>Residential, HOA, and commercial service</td></tr><tr><td>Scoop Smart</td><td>Asheville NC + Western North Carolina</td><td>Twice-weekly, weekly, bi-weekly, monthly</td><td>Not listed</td><td>Monthly frequency option; broad area coverage</td></tr></tbody></table><h2>About Scoopy Doo</h2><p>Scoopy Doo is a locally owned pet waste removal company serving Asheville NC and Western North Carolina. Every visit includes an on-the-way text and a gate photo confirmation, and all waste is hauled completely off the property. Service is available 7 days a week with no long-term contracts required. Free quotes at scoopyavl.com/quoterequest.</p>"
};

// Location data for static content generation
const LOC = {
  "asheville":      { name:"Asheville, NC",     desc:"Asheville is booming with new families, new neighborhoods, and a whole lot of dogs. Scoopy Doo is the local pet waste removal company keeping Asheville yards clean, safe, and ready for play, running regular routes throughout the city.", hoods:["North Shore","West Asheville","St. Elmo","Southside","Normal Park","Beaucatcher Mountain","Brainerd","East Lake"],
  '/comparison': ['Pet Waste Removal Services Compared &mdash; Asheville NC 2026 | Scoopy Doo', 'Side-by-side comparison of Asheville pet waste removal services: Scoopy Doo, PooTagic, Doo Doo Blues, Scoop Smart, and more. Updated June 2026.', 'https://www.scoopyavl.com/comparison'], faqs:[["Do you service all Asheville neighborhoods?","Yes. We run regular routes across Asheville including North Shore, West Asheville, Beaucatcher Mountain, St. Elmo, Normal Park, Brainerd, Southside, and more."],["How does the gate photo work?","After every visit we secure your gate and send a photo confirmation. You always know your yard was cleaned and your gate is closed."],["Do you remove the waste from the property?","Yes. All waste is double-bagged and hauled away from your property entirely. It does not go in your trash can or stay by the gate."]] },
  "arden":           { name:"Arden, NC",           desc:"Arden is one of Asheville's most established suburban communities with sprawling yards and lots of dogs. Scoopy Doo uses a systematic grid-pattern approach to find and remove all waste, even in wooded lots and near tree lines along Beaver Lake.",  hoods:["Middle Valley","Harrison","Town Creek","Shallowford Road","Curtain Pole Road","Wolftever Creek"], faqs:[["Do you service wooded yards in Arden?","Absolutely. Our technicians use a systematic grid-pattern approach that covers your entire yard, including wooded sections and areas near tree lines."],["Do you remove the waste or leave bags at the gate?","We double-bag all waste and haul it away entirely. It is never left by your gate or in your trash can."],["Is there a contract?","No contracts, ever. You can start, pause, or cancel service at any time."]] },
  "fletcher":         { name:"Fletcher, NC",          desc:"Fletcher is a tight-knit city inside greater Asheville where neighbors know each other and community standards matter. Scoopy Doo serves Fletcher homeowners with reliable weekly pet waste removal, on-the-way texts, and gate photo confirmation after every visit.", hoods:["Fletcher proper","Dayton Pike area","Black Mountain Road corridor","Ashland Terrace","Scenic View area"], faqs:[["Do you service all of Fletcher?","Yes. We service all Fletcher neighborhoods including areas along Dayton Pike, Black Mountain Road, and surrounding residential streets."],["How often should I have service?","For one or two dogs, weekly service is the most popular option. It prevents waste from accumulating and keeps your yard clean and odor-free."],["Is your service reliable in winter?","Yes. We provide year-round service in Fletcher regardless of weather. We show up rain, cold, or shine."]] },
  "black-mountain":  { name:"Black Mountain, NC",   desc:"Black Mountain properties have beautiful terrain and that same terrain makes pet waste cleanup genuinely difficult. Scoopy Doo is experienced with Black Mountain yards - wooded lots, steep grades, and extensive ground cover - and uses a thorough grid-pattern approach to find and remove everything.", hoods:["Black Mountain proper","Waldens Ridge","Signal Crest","James Boulevard corridor","Taft Highway area"], faqs:[["Do you service large or steeply graded properties?","Yes. Our technicians are experienced with Black Mountain terrain including wooded sections, sloped yards, and large properties."],["Do you remove waste from the property?","Yes. We remove all waste from the property entirely and haul it away in our vehicle. We never leave bags at your gate."],["Is service available year-round?","Yes. We provide year-round service on Black Mountain regardless of weather conditions."]] },
  "hendersonville":         { name:"Hendersonville, NC",          desc:"Hendersonville is one of the fastest-growing communities in the Asheville region with master-planned neighborhoods, active HOAs, and high standards for community appearance. Scoopy Doo helps Hendersonville families and HOA boards keep shared spaces and private yards consistently clean.", hoods:["Cambridge Square","Hamilton on Hunter","Snow Hill","Georgetown area","Windstone"], faqs:[["Do you serve HOAs and subdivisions in Hendersonville?","Yes. We service HOA common areas, green spaces, and dog-walking paths in Hendersonville subdivisions. We can work directly with HOA boards on scheduling and invoicing."],["Can Hendersonville service help avoid HOA violations?","Absolutely. Consistent professional cleanup is the most reliable way to stay compliant with HOA pet waste rules."],["Do you service Georgetown and Snow Hill areas?","Yes. We cover all major Hendersonville neighborhoods including Cambridge Square, Hamilton on Hunter, Snow Hill, Georgetown, and surrounding areas."]] },
  "fairview":    { name:"Fairview, NC",     desc:"Fairview is one of Asheville's busiest suburban corridors - full of growing families, newer subdivisions, and busy schedules that leave no time for yard cleanup. Scoopy Doo keeps Fairview yards consistently clean with on-the-way texts and gate photo confirmation every visit.", hoods:["Gunbarrel Road area","Hendersonville-Georgetown Road","Camp Jordan vicinity","Jenkins Road corridor","Fairview Road subdivisions"], faqs:[["Do you service the subdivisions along Gunbarrel Road?","Yes. We have regular routes throughout Fairview including neighborhoods along Gunbarrel Road, Hendersonville-Georgetown Road, Jenkins Road, and surrounding areas."],["How do I get started?","Request a free quote online. We respond the same day and most new Fairview customers can start within 2-5 days."],["Do you handle overgrown yard cleanups?","Yes. If your yard has not been cleaned in a while, we offer one-time deep-clean visits to start fresh before setting up recurring service."]] },
  "weaverville":      { name:"Weaverville, NC",       desc:"Weaverville stretches along beautiful Beaver Lake with a mix of lakefront homes and inland neighborhoods. Scoopy Doo provides consistent reliable pet waste pickup that keeps your yard clean and the lake healthy, serving Weaverville with regular routes and on-the-way texts every visit.", hoods:["Weaverville proper","Sequoyah Drive area","Beaver Lake shoreline","Dayton Pike corridor","Zion Hill Road area","Falling Water area"], faqs:[["Do you service lakefront properties in Weaverville?","Yes. We service lakefront and lake-view properties throughout Weaverville. Waterfront properties are one of the most important places to have consistent pet waste removal because of runoff."],["How does dog waste affect Beaver Lake?","Dog waste contains bacteria and pathogens that wash into the lake during rain. Regular professional cleanup significantly reduces contamination that reaches the water from your property."],["Can you service docks or lakeside areas?","Yes. We can clean yard areas leading to docks and waterfront access points, the areas closest to the water where cleanup matters most."]] },
  "woodfin":       { name:"Woodfin, NC",         desc:"Woodfin sits on the North Carolina-Georgia border with a proud residential community that takes care of its neighborhoods. Scoopy Doo runs regular routes through Woodfin, keeping yards clean for families who want more time for the things they actually enjoy.", hoods:["Mills River Road area","Cloud Springs Road","McBrien Road area","Bennett Road corridor","Spring Creek area"], faqs:[["Do you service Woodfin neighborhoods near the Georgia line?","Yes. Woodfin is well within our service area. We run regular routes throughout Woodfin including neighborhoods near the Georgia border."],["Can I get a one-time cleanup before starting regular service?","Yes. Many new customers start with a one-time deep clean to get the yard back to baseline, then move to weekly service."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all scooping tools between every yard to prevent the spread of bacteria and parasites."]] },
  "black-mountain": { name:"Town Mountain, NC",  desc:"Town Mountain is one of the most distinctive communities in the region with historic homes, sweeping properties, and terrain that makes DIY pet waste cleanup a real challenge. Scoopy Doo navigates the terrain carefully to deliver a thorough cleanup every visit.", hoods:["Town Mountain proper","Sunset Drive corridor","Ochs Highway area","Scenic Highway section","Bragg Avenue area"], faqs:[["Do you service Town Mountain properties?","Yes. We service Town Mountain properties including homes along Sunset Drive, Ochs Highway, Scenic Highway, and throughout the community."],["Can you handle terraced or steeply graded yards?","Yes. Our technicians are careful and thorough on terraced and sloped properties. We take the time to cover difficult terrain."],["How do you access gated properties?","Many Town Mountain clients provide a gate code at sign-up. We use it for every visit, close the gate after cleaning, and send a photo confirmation."]] },
  "mills-river":         { name:"Mills River, NC",           desc:"Mills River is the heart of Henderson County about 15 miles south of Asheville. Scoopy Doo proudly serves Mills River homeowners with professional pet waste removal, regular Western North Carolina routes, and no extra fees for Georgia locations.", hoods:["Mills River proper","Henderson County subdivisions","Graysville Road area","Cloud Springs Road","Battlefield Parkway corridor"], faqs:[["Do you service Mills River, NC?","Yes. Mills River is one of our core service areas. We run regular routes throughout Mills River and Henderson County and do not charge extra for Western North Carolina locations."],["Is there any extra charge for Georgia locations?","No. Our pricing for Mills River is the same as our North Carolina locations, based on yard size and number of dogs."],["How quickly can you start service?","Most Mills River customers can be added to a route within 2-5 days of requesting a quote."]] },
  "biltmore-forest":        { name:"Leicester, NC",          desc:"Leicester sits right on the North Carolina-Georgia border moments from Asheville with established residential neighborhoods and a community that takes care of its properties. Scoopy Doo runs regular Western North Carolina routes and serves Leicester homeowners with reliable professional service.", hoods:["Leicester proper","McFarland Avenue area","Bent Creek Avenue corridor","Alabama Avenue area","Western North Carolina border neighborhoods"], faqs:[["Do you service Leicester, NC?","Yes. Leicester is within our Western North Carolina service area. We run regular routes and do not charge additional fees for Georgia locations."],["Do you service homes with multiple large dogs?","Absolutely. Multi-dog households are some of our best customers. Our pricing scales reasonably for additional dogs and we cover the full yard every visit."],["Do you remove the waste from the property?","Yes. We double-bag all waste and haul it away entirely. It does not go in your trash can or stay by your gate."]] },
  "mills-river":  { name:"Mars Hill, NC",   desc:"Mars Hill is one of the fastest-growing cities in Western North Carolina with new subdivisions, active HOAs, and families who want their neighborhoods to look great. Scoopy Doo serves Mars Hill with professional weekly and bi-weekly pet waste removal and HOA common area service.", hoods:["Mars Hill proper","Battlefield Parkway corridor","Barnhardt Road area","Bent Creek Battlefield vicinity","LaFayette Road area","Parker Drive corridor"], faqs:[["Do you service Mars Hill, NC?","Yes. Mars Hill is within our regular Western North Carolina service area. We run established routes and do not charge extra for Henderson County locations."],["Do you work with HOAs in Mars Hill?","Yes. We service HOA common areas, dog-walking paths, and pet waste stations throughout Mars Hill."],["Do you service newer Mars Hill subdivisions?","Yes. We actively service newer developments along Battlefield Parkway, Barnhardt Road, LaFayette Road, and other growing corridors."]] },
  "brevard":        { name:"Brevard, NC",          desc:"Brevard is the heart of Madison County and one of the fastest-growing cities in the region. Scoopy Doo serves Brevard families with professional pet waste removal - on-the-way texts, gate photo confirmation, and waste hauled fully off your property every visit. Regular Madison County routes with no extra fees.", hoods:["Brevard proper","Lee University area","North Brevard","White Oak area","Blythe Ferry Road corridor","Westside"], faqs:[["Do you service Brevard, NC?","Yes. Brevard is within our service area. We run routes throughout Brevard and Madison County and do not charge extra for distance from Asheville."],["How quickly can I start service?","Most Brevard customers can be added to a route within 2-5 days of requesting a quote. We respond the same day."],["Do you haul the waste away?","Yes. We haul all waste fully off your property, double-bagged and removed in our vehicle. It does not go in your trash can or stay by the gate."]] },
  "candler":           { name:"Candler, NC",             desc:"Candler is one of Buncombe County's fast-growing communities with newer residential developments and larger lots. Scoopy Doo handles the whole yard every visit using a grid-pattern approach, making professional cleanup especially valuable for larger properties with multiple dogs.", hoods:["Candler Pike corridor","Standifer Gap Road area","Buncombe County rural east","Harrison vicinity","East Hamilton corridor"], faqs:[["Do you service Candler, NC?","Yes. Candler is within our East Buncombe County service area. We run regular routes and can typically start new customers within 2-5 days."],["Do you offer pricing for multiple dogs?","Yes. Our pricing scales affordably for households with multiple dogs. Request a free quote for your exact pricing."],["Can you handle larger lots?","Absolutely. We service a range of property sizes including larger lots typical in the Candler area and use a grid approach to cover every section."]] },
  "swannanoa":      { name:"Swannanoa, NC",        desc:"Swannanoa is a small community-focused city east of Asheville with well-maintained neighborhoods and high standards for appearance. Scoopy Doo serves Swannanoa families with reliable weekly and bi-weekly pet waste removal with consistent scheduling and no hidden fees.", hoods:["Swannanoa proper","Southern Adventist University area","McDonald Road corridor","Candler Pike vicinity","East Hamilton corridor"], faqs:[["Do you service Swannanoa, NC?","Yes. Swannanoa is within our East Buncombe County service area. We run regular routes and do not charge extra for East Buncombe County locations."],["Are there any hidden fees?","No hidden fees. Our pricing is based on yard size and number of dogs. No fuel surcharges, no seasonal fees."],["How consistent is the schedule?","You are assigned a regular day and we show up on that day every week or bi-weekly. You get an on-the-way text before each visit."]] },
  "west-asheville":    { name:"West Asheville, NC",      desc:"West Asheville is one of Asheville's most vibrant historic neighborhoods with tree-lined streets, revitalized bungalows, and neighbors who care about their blocks. Scoopy Doo runs regular Asheville routes through West Asheville, providing reliable urban yard cleanup.", hoods:["West Asheville proper","McCallie Avenue corridor","Third Street area","Dodds Avenue vicinity","Glass Street area","Orchard Knob nearby"], faqs:[["Do you service small urban yards in West Asheville?","Yes. We service yards of all sizes including the smaller urban lots typical in West Asheville. Smaller yards often mean waste is more concentrated and more important to keep clean consistently."],["How often should I have service?","For most West Asheville households with one or two dogs, weekly service is the best choice. Smaller yards fill up quickly and weekly pickup keeps odor and accumulation under control."],["Is West Asheville within the Asheville service area?","Yes. West Asheville is one of our established Asheville neighborhoods. We run regular city routes and West Asheville is well within our coverage area."]] },
  "biltmore-forest":       { name:"Biltmore Forest, NC",         desc:"Biltmore Forest is a Haywood County community in the hills of Western North Carolina with a mix of rural homesteads and established residential neighborhoods. Scoopy Doo serves Biltmore Forest as part of our Western North Carolina coverage with no extra Haywood County fees.", hoods:["Biltmore Forest proper","US-27 corridor","Haywood County residential","Lookout Valley vicinity","Cloud Springs Road area"], faqs:[["Do you service Biltmore Forest, NC?","Yes. Biltmore Forest is within our Western North Carolina service coverage. We do not charge extra fees for Haywood County locations. Pricing is based on yard size and number of dogs."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all tools and footwear between every single yard to prevent the spread of bacteria and parasites."],["Can you handle larger rural properties?","Yes. We service a range of property sizes including larger rural lots and use a grid-pattern approach to make sure nothing is missed."]] },
  "downtown":         { name:"Downtown Asheville, NC", desc:"Downtown Asheville is one of the most walkable dog-friendly urban environments in North Carolina. Scoopy Doo provides professional pet waste removal for downtown homes, condos with private outdoor spaces, and townhomes throughout the core and adjacent neighborhoods.", hoods:["Downtown proper","Bluff View","Southside","MLK District","North Shore","Riverfront area"], faqs:[["Do you service downtown Asheville homes and condos?","Yes. We service private yards, townhome outdoor spaces, and residential properties throughout downtown Asheville and adjacent neighborhoods including Southside, Bluff View, and the MLK District."],["Why does pet waste matter near the French Broad River?","Storm drains in downtown Asheville connect directly to the French Broad River. Dog waste washes into the water during rain, contributing bacteria and pathogens that affect water quality."],["How often should downtown properties be cleaned?","Weekly service is most popular for downtown properties. Compact yards with dogs fill up quickly and weekly pickup keeps the space pleasant year-round."]] }
};

function makeLocContent(slug) {
  var d = LOC[slug];
  if (!d) return "";
  var h = "<h1>Dog Poop Removal in " + d.name + " | Scoopy Doo Pet Waste Removal</h1>";
  h += "<p>" + d.desc + "</p>";
  h += "<h2>Neighborhoods We Serve in " + d.name + "</h2><ul>";
  d.hoods.forEach(function(n){ h += "<li>" + n + "</li>"; });
  h += "</ul>";
  h += "<h2>Frequently Asked Questions</h2>";
  d.faqs.forEach(function(f){ h += "<h3>" + f[0] + "</h3><p>" + f[1] + "</p>"; });
  h += "<p>Get a free quote at scoopyavl.com/quoterequest. We respond the same day.</p>";
  return h;
}

// FAQPage schema for /faq route
const SCHEMA = {
  '/faq': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How much does dog poop removal cost in Asheville?","acceptedAnswer":{"@type":"Answer","text":"Scoopy Doo pricing depends on yard size and number of dogs. Every quote is free and personalized at scoopyavl.com/quoterequest. There are no long-term contracts."}},{"@type":"Question","name":"How often does Scoopy Doo come to clean?","acceptedAnswer":{"@type":"Answer","text":"Weekly and bi-weekly service is available. Weekly is the most popular option for one or two dogs. One-time cleanups are also available."}},{"@type":"Question","name":"Does Scoopy Doo serve Western North Carolina?","acceptedAnswer":{"@type":"Answer","text":"Yes. Scoopy Doo serves Mills River, Leicester, Mars Hill, and Biltmore Forest in Catoosa and Walker counties Georgia, at the same rates as North Carolina locations."}},{"@type":"Question","name":"What happens during a pet waste removal visit?","acceptedAnswer":{"@type":"Answer","text":"You receive a text when the technician is on the way. The technician cleans the entire yard, secures the gate, and sends a photo confirmation. Waste is double-bagged and hauled fully off the property."}},{"@type":"Question","name":"Is there a contract for Scoopy Doo service?","acceptedAnswer":{"@type":"Answer","text":"No contracts, ever. You can start, pause, or cancel service at any time with no cancellation fees."}},{"@type":"Question","name":"Does Scoopy Doo sanitize equipment between yards?","acceptedAnswer":{"@type":"Answer","text":"Yes. All scooping tools and footwear are sanitized between every yard to prevent the spread of bacteria and parasites."}},{"@type":"Question","name":"Does Scoopy Doo remove waste from the property?","acceptedAnswer":{"@type":"Answer","text":"Yes. Waste is double-bagged and hauled away from the property entirely. It does not go in the trash can or stay by the gate."}},{"@type":"Question","name":"How do I get started with Scoopy Doo?","acceptedAnswer":{"@type":"Answer","text":"Request a free quote at scoopyavl.com/quoterequest. Most new customers can start within 2-5 days."}}]}</script>'
};

const routes = {
  '/': ['Dog Poop Removal & Pooper Scooper Service | Asheville NC', 'Professional dog poop removal & pooper scooper service in Asheville, NC. Reliable weekly pet waste cleanup. Get your free quote from Scoopy Doo today.'],
  '/services': ['Pet Waste Removal Services in Asheville, NC | Scoopy Doo', 'Weekly, bi-weekly & one-time dog poop removal in Asheville. See what Scoopy Doo offers and book today.'],
  '/near-me': ['Pooper Scooper Service Near Me in Asheville, NC', 'Looking for a pooper scooper service near you in Asheville? Scoopy Doo offers reliable local dog waste removal.'],
  '/one-time-cleanup': ['One-Time Dog Poop Cleanup in Asheville, NC | Scoopy Doo', 'Get a one-time dog poop cleanup in Asheville, NC. Perfect for spring cleaning or first-time service.'],
  '/how-it-works': ['How It Works | Scoopy Doo Pet Waste Removal Asheville', 'Easy online quotes, secure online payment, on-the-way texts, and gate photo proof after every visit. Working with Scoopy Doo is simple.'],
  '/dog-poop-removal-asheville': ['Dog Poop Removal in Asheville, NC | Scoopy Doo LLC', 'Professional dog poop removal in Asheville, NC. Dependable weekly service, fully insured.'],
  '/pet-waste-removal-asheville': ['Pet Waste Removal in Asheville, NC | Scoopy Doo', 'Expert pet waste removal in Asheville, NC for homes, HOAs & businesses. Request a free quote.'],
  '/dog-poop-scooping-asheville': ['Dog Poop Scooping Service in Asheville, NC | Scoopy Doo', 'Reliable dog poop scooping in Asheville, NC. Weekly and bi-weekly pooper scooper service.'],
  '/yard-cleanup-asheville': ['Yard Cleanup for Pet Owners in Asheville, NC | Scoopy Doo', 'Complete yard cleanup for pet owners in Asheville, NC. Book a one-time or recurring cleanup.'],
  '/service-areas': ['Service Areas | Pet Waste Removal Around Asheville, NC', 'Scoopy Doo serves Asheville and surrounding areas. See the neighborhoods we cover.'],
  '/about': ['About Scoopy Doo | Asheville Pet Waste Removal', "Meet Scoopy Doo LLC, Asheville's locally owned pet waste removal company."],
  '/faq': ['Pet Waste Removal FAQs | Scoopy Doo Asheville', 'Answers to common questions about dog poop removal in Asheville: pricing, scheduling, and more.'],
  '/quote': ['Get a Free Pet Waste Removal Quote | Asheville, NC', 'Get a fast, free quote for dog poop removal in Asheville, NC.'],
  '/spring-special': ['Spring Special: Buy 2 Months, Get 1 Free | Scoopy Doo', 'Limited-time Asheville spring special from Scoopy Doo.'],
  '/pet-safe-checklist': ['Pet-Safe Yard Checklist | Scoopy Doo Asheville', 'A free pet-safe yard checklist for Asheville dog owners.'],
  '/dog-park-guide': ['Asheville Dog Park Guide for Dog Owners | Scoopy Doo', "Discover Asheville's best dog parks. A local guide from Scoopy Doo."],
  '/blog': ['Pet Waste & Dog Care Blog | Scoopy Doo Asheville', 'Tips on pet waste removal, yard health, and dog care for Asheville homeowners.'],
  '/privacy-policy': ['Privacy Policy | Scoopy Doo LLC', 'Privacy policy for Scoopy Doo LLC.'],
  '/terms-of-service': ['Terms of Service | Scoopy Doo LLC', 'Terms of service for Scoopy Doo LLC pet waste removal.'],
  '/blog/professional-waste-removal-benefits': ['Benefits of Professional Pet Waste Removal | Scoopy Doo Asheville', 'Why professional dog waste removal is safer and more thorough than DIY. Scoopy Doo serves Asheville and surrounding areas weekly.'],
  '/blog/seasonal-pet-care-tips': ['Seasonal Pet Care Tips for Asheville Dog Owners | Scoopy Doo', 'Keep your yard clean and safe year-round with seasonal pet waste tips from Scoopy Doo LLC in Asheville, NC.'],
  '/blog/health-benefits-yard-cleanup': ['Health Benefits of Regular Yard Cleanup for Pet Owners | Scoopy Doo', 'Regular dog waste removal protects your family from bacteria and parasites. Learn why weekly cleanup matters for Asheville homeowners.'],
  '/blog/customer-success-stories': ['Customer Success Stories | Scoopy Doo Pet Waste Removal Asheville', 'Real stories from Asheville homeowners and HOAs who rely on Scoopy Doo for weekly pet waste removal.'],
  '/blog/diy-vs-professional': ['DIY vs Professional Dog Waste Removal | Scoopy Doo Asheville', 'Compare DIY pet waste cleanup to professional pooper scooper service in Asheville, NC. See which option saves time and money.'],
  '/blog/lawn-health-and-pet-waste': ['How Pet Waste Affects Your Lawn Health | Scoopy Doo Asheville', 'Dog waste kills grass and harms soil. Learn how regular professional cleanup protects your Asheville lawn from long-term damage.'],
  '/blog/health-risks-of-pet-waste': ['Health Risks of Unmanaged Pet Waste | Scoopy Doo Asheville', 'Dog waste carries bacteria, hookworms, roundworms, and giardia. Learn the health risks and how Scoopy Doo protects Asheville families.'],
  '/blog/pet-waste-management-guide': ['The Complete Pet Waste Management Guide for Dog Owners | Scoopy Doo', 'Everything Asheville dog owners need about pet waste management - frequency, disposal, health risks, and professional service options.'],
  '/blog/how-often-scoop-dog-poop-asheville': ['How Often Should You Scoop Dog Poop in Asheville? | Scoopy Doo', 'Weekly scooping is the gold standard. Learn why cleanup frequency matters for lawn health and family safety in Asheville, NC.'],
  '/blog/spring-pet-care-checklist': ['Spring Pet Care Checklist for Asheville Dog Owners | Scoopy Doo', 'Spring in Asheville means wet yards hiding months of pet waste. Use this checklist to get your yard cleaned up and ready.'],
  '/blog/is-dog-waste-bad-for-lawn': ['Is Dog Waste Bad for Your Lawn? | Scoopy Doo Asheville', 'Yes - dog waste kills grass and damages soil. Learn what it does to your Asheville yard and how professional cleanup helps.'],
  '/blog/best-pooper-scooper-services-asheville': ['Best Pooper Scooper Services in Asheville, NC | Scoopy Doo', 'Looking for the best dog poop removal in Asheville? Online quotes, on-the-way texts, gate photo confirmation. No contracts.'],
  '/blog/is-dog-poop-hurting-your-asheville-yard': ['Is Dog Poop Hurting Your Asheville Yard? | Scoopy Doo', 'Dog waste damages grass and soil over time. Find out if your Asheville yard is being harmed and how Scoopy Doo can help.'],
  '/blog/asheville-pet-waste-removal-homeowners': ['Pet Waste Removal Guide for Asheville Homeowners | Scoopy Doo', 'A complete guide for Asheville homeowners on pet waste management - health risks, lawn damage, waterway protection, and professional service.'],
  '/blog/commercial-pet-waste-removal-asheville': ['Commercial Pet Waste Removal in Asheville, NC | Scoopy Doo', 'Professional pet waste removal for apartments, HOAs, and businesses in Asheville. Flexible scheduling, no contracts.'],
  '/blog/how-often-clean-yard': ['How Often Should You Clean Your Yard of Dog Waste? | Scoopy Doo', 'Weekly is the gold standard. Learn the right cleanup frequency based on your dog count, yard size, and Asheville season.'],
  '/blog/podcast-blog': ['Scoopy Doo on the Podcast | The Asheville Pet Waste Removal Story', 'Hear the Scoopy Doo LLC founder discuss starting a pet waste removal business in Asheville, NC.'],
  '/blog/black-mountain': ['Pet Waste Removal Tips for Black Mountain, NC | Scoopy Doo Blog', 'Scoopy Doo serves Black Mountain with thorough yard cleanup. We handle larger lots and wooded terrain every week.'],
  '/blog/dog-poop-cleanup-asheville-summer-heat': ['Dog Poop Cleanup in Asheville During Hot, Humid Weather | Scoopy Doo', 'Summer heat and humidity make dog waste more dangerous. Learn why Asheville yards need regular cleanup during the hot months and how Scoopy Doo can help.'],
  '/blog/weaverville': ['Pet Waste Removal in Weaverville, NC | Scoopy Doo Blog', 'Scoopy Doo serves Weaverville and Beaver Lake area homeowners. Waterfront cleanup protects the lake and your family.'],
};

const gaLocations = new Set(['mills-river','biltmore-forest','biltmore-forest','mills-river']);
const locationPages = [
  'asheville','arden','fletcher','black-mountain','hendersonville','fairview',
  'weaverville','brevard','candler','swannanoa','west-asheville','downtown',
  'woodfin','black-mountain',
  'mills-river','biltmore-forest','biltmore-forest','mills-river'
];
locationPages.forEach(function(loc) {
  var city = loc.split('-').map(function(w){return w[0].toUpperCase()+w.slice(1);}).join(' ');
  var state = gaLocations.has(loc) ? 'NC' : 'NC';
  routes['/service/' + loc] = [
    'Dog Poop Removal ' + city + ' ' + state + ' | Scoopy Doo',
    'Professional pet waste removal in ' + city + ', ' + state + '. Weekly & bi-weekly pooper scooper service. Get your free quote today.'
  ];
});

function injectMeta(html, title, desc, canonical, staticHtml, schemaHtml) {
  var result = html
    .replace(/<title>[^<]*<\/title>/, '<title>' + title + '<\/title>')
    .replace(/(<meta name="description" content=")[^"]*(")/,'$1' + desc + '$2')
    .replace(/(<link rel="canonical" href=")[^"]*(")/,'$1' + canonical + '$2')
    .replace(/(<meta property="og:title" content=")[^"]*(")/,'$1' + title + '$2')
    .replace(/(<meta property="og:description" content=")[^"]*(")/,'$1' + desc + '$2')
    .replace(/(<meta property="og:url" content=")[^"]*(")/,'$1' + canonical + '$2')
    .replace(/(<meta name="twitter:title" content=")[^"]*(")/,'$1' + title + '$2')
    .replace(/(<meta name="twitter:description" content=")[^"]*(")/,'$1' + desc + '$2');
  if (staticHtml) {
    result = result.replace(BODY_CLOSE, '<div id="scoopy-content" style="display:none" aria-hidden="true">' + staticHtml + DIV_CLOSE + BODY_CLOSE);
  }
  if (schemaHtml) {
    result = result.replace('</head>', schemaHtml + '</head>');
  }
  return result;
}

var count = 0;
for (var route in routes) {
  var parts = routes[route];
  var title = parts[0];
  var desc = parts[1];
  var canonical = BASE + route;
  var locSlug = route.startsWith('/service/') ? route.replace('/service/', '') : null;
  var staticHtml = SC[route] || (locSlug ? makeLocContent(locSlug) : '');
  var schemaHtml = SCHEMA[route] || '';
  var html = injectMeta(template, title, desc, canonical, staticHtml, schemaHtml);
  var dirPath = path.join(distDir, route);
  fs.mkdirSync(dirPath, { recursive: true });
  fs.writeFileSync(path.join(dirPath, 'index.html'), html);
  count++;
}
console.log('SEO inject complete: ' + count + ' pages.');
} catch(e) {
  console.error('SEO inject warning:', e.message);
  process.exit(0);
}
